appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
bot: {automerge: true}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default, win: azure}
travis:
  secure: {BINSTAR_TOKEN: qXmqNpexDCn1SI/cLaMaxwOuosH5I0TgbJQupHQNmXIFdIkTmKFVqrtuqdH20IRh8M7RmsNTKirijVnZ+zrSQXOJNzZFrM6Wgmnq8AJFsohhjyLrzufRVSO8rXqPxmJsXUFamy8AsMx1+1Xit8uewb5aKi9RjBpSEC6NFyXwkOvSCJhy0uNUOu6nLoVNjkQhbl9vuxAduaoMJ1jWF0tTEEEk2ugwypCsYc80l6+79NyKq4r8C1/42hLYWgkdfvF/uLa5Do1MIAlfA8aMx/9WjhzZpWnof13xvUuvOn1ncmmnx76306xBTYudnyuF9weQMZMGlS0hfWlaUf7Pi0W8FXY85+Xd+aiSryqDg+dPrlqnjiwIV7CmTgcn0quLK2KTSpQICv5uPC/MREm1bcqx4DoF20aKoPZ0XoGKTUJNW/LlPdFXy4+x3nn6ldGdQ4dS3NdLsCFnW/mTCnArNCms+pB7+vIT8ZxqnkLYgJDlUbhSBBFLWCjFYS5M0igjXAbJtgU9wQiFlAmPUu0GSe9d/goR6WuL+0gD5X4BzTDTQspfV9IcP77DjGwLN1mMnn2oTmLbrLMyVwtojRZXcGgBV3avvVGgE47FoI6tmA8sYQ+xEoVrZ6fPJ0uznuga7fkTNEYn+K4WIv6plvxNNU7hBL0e/Ic2wHhZj/IEaxCVpdM=}
